language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - rpocklin@gmail.com
matrix:
  allow_failures:
services:
  - redis-server